name: Like a Tweet containing \#Photography

on:
  schedule:
    - cron: "*/15 * * * *" # Every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo content to GitHub runner
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.5" # Install the Python version needed

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          KEYS: ${{ secrets.KEYS }}
        run: python -c "from actions import *; action_like_tweet_contains("#photography")"
